# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CgpRbqLLnsY_KmLjbzSikgyqgnGzdA5
"""

pip install opencv_python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("rasm1.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv_python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("rasm2.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv_python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("rasm3.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv_python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("rasm4.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv_python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("rasm5.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)